"""auto-add-phone-number-to-users

Revision ID: 57e5f5bd4c5a
Revises: 73ecda8b23a6
Create Date: 2023-02-14 14:47:28.935225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e5f5bd4c5a'
down_revision = '73ecda8b23a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
