name: Build and Deploy Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 0014031681
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: c4f266b7d659fa8bb24341267af49c85981291e41784b02d0937aae778431c69
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3.3.0
      - name: Install Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
      - name: upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip3 install -r requirements.txt
      - name: Running Unit-test
        run: |
          pip3 install pytest
          pytest
